name: app_taller_rl
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.1
  http: ^1.2.0
  supabase_flutter: ^2.3.2
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  intl: ^0.19.0
  google_fonts: ^6.1.0
  animate_do: ^3.3.2
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_logo_taller_300x300.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/app_logo_taller_300x300.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
